name: project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.11
  go_router: ^14.3.0
  flutter_onboarding_slider: ^1.0.11
  curved_navigation_bar: ^1.0.6
  iconly: ^1.0.1
  font_awesome_flutter: ^10.8.0
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  flutter_bloc: ^9.0.0
  modal_progress_hud_nsn: ^0.5.1
  file: ^7.0.1
  flutter_downloader: ^1.11.8
  permission_handler: ^11.4.0
  quickalert: ^1.1.0
  file_picker: ^9.0.0
  open_file: ^3.5.10
  flutter_plugin_android_lifecycle: ^2.0.15
  meta: ^1.15.0
  fluttertoast: ^8.2.2
  http_parser: ^4.0.2
  equatable: ^2.0.7
  path_provider: ^2.1.5
  flutter_spinkit: ^5.2.1
  lottie: ^3.2.0
  flutter_file_downloader: ^2.1.0
  device_info_plus: ^11.3.0
  foundation: ^0.0.5
  url_launcher: ^6.3.1
  universal_html: ^2.2.4
  image_picker: ^1.1.2
  flutter_pdfview: ^1.4.0+1
  syncfusion_flutter_pdfviewer: ^29.1.38
  dio: ^5.8.0+1
  flutter_launcher_icons: ^0.14.4
  filter_list: ^1.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/groupp.png"
